version: '3.8'

services:
  tic-tac-toe:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - random_api_base_url=http://random-service:5000  

  random-service:
    image: maguirebrendan/random:latest
    ports:
      - "5000:5000"
